const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.join(__dirname,'..');
const source=fs.readFileSync(path.join(root,'online.js'),'utf8');
new vm.Script(source,{filename:'online.js'});
const sandbox={console,Uint8Array,URL,globalThis:null,location:{protocol:'file:',href:'file:///C:/Astra/index.html'}};sandbox.globalThis=sandbox;sandbox.window=sandbox;
vm.runInNewContext(source,sandbox);
const t=sandbox.AstraOnline._test;
assert.equal(t.normalizeRoomCode(' ab-01ioz9 '),'ABZ9');
assert.equal(t.generateRoomCode(Uint8Array.from([0,1,2,3,4,5,6,7])),'ABCDEFGH');
assert.equal(t.safeName('  <小\u0000明>  '),'小明');
assert.equal(t.safeMessage('  你好\n  星屿  '),'你好 星屿');
assert.deepEqual(JSON.parse(JSON.stringify(t.sanitizePose({x:1,y:2,z:3,heading:4,speed:5,kind:'drive',region:'harbor'}))),{x:1,y:2,z:3,heading:4,speed:5,kind:'drive',region:'harbor'});
assert.equal(t.sanitizePose({x:Infinity,y:2,z:3,heading:0,speed:0}),null);
assert.equal(t.validPeer({id:'short',name:'A',pose:{x:0,y:0,z:0,heading:0,speed:0}}),null);
assert(t.validPeer({id:'abcdefgh',name:'A',color:7,pose:{x:0,y:0,z:0,heading:0,speed:0}}));
assert.equal(t.roomUrl('ABCDEFGH').href,'https://yzouj0031-hub.github.io/Astra/?room=ABCDEFGH');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
for(const token of ['id="online-button"','id="online-dialog"','src="./online.js"','AstraOnline?.init','animateRemotePlayers(dt,t)'])assert(html.includes(token),`Missing online integration: ${token}`);
const server=fs.readFileSync(path.join(root,'scripts','serve.mjs'),'utf8');assert(server.includes("['/online.js'"),'Local server exposes the online client');
console.log('Online co-op: room validation, untrusted payload filtering, UI/world wiring and local serving passed');
